### ISSUE TITLE
Copper: document how to adjust layoutConfig

### ISSUE THREAD

**Issue by eiswind** [orchidhq/Orchid#346]
The CopperTheme has some variables like

``` {% if layoutConfig.includeBreadcrumbs %}```

I tried to understand the code from:

```
fun getLayoutConfig(layoutName: String, data: Map<String, Any>?): Any? {
        return when(layoutName) {
            "homepage" -> CopperHomepageLayoutConfig().also { it.extractOptions(context, data) }
            else -> CopperSidebarLayoutConfig().also { it.extractOptions(context, data) }
        }
    }
```

But still I do not have any clue how to set these parameters.

It would be great if this could get some documentation.

**Comment by cjbrooks12** [comment]
The implementation of these "layout configs" is still very much a work-in-progress. You're welcome to customize them yourself, but how they work is likely going to change in future releases. I'll make sure to include in release notes if/when they change, so it shouldn't surprise you.

There are currently only configurations available for the default layout from Copper. No other layouts or themes use them, currently. The main idea is that the configurations are provided individually from each page, either in its Front Matter or from an Archetype. Basically, they're used alongside the existing `layout` property for pages.

The available options are defined [in this file](https://github.com/orchidhq/Orchid/blob/dev/themes/OrchidCopper/src/main/kotlin/com/eden/orchid/copper/CopperTheme.kt#L201-L211), but you can also see them in the admin panel at [this URL](http://localhost:8080/admin/describe?className=com.eden.orchid.copper.CopperSidebarLayoutConfig) when it's running locally. 

Here's a snippet showing how you'd customize the layout configs for static pages, for example:

```yaml
# config.yml
pages:
  staticPages:    # <-- Static pages Archetype key
    layoutConfig: # <-- configures the default Copper layout for static pages
      wrapPageInBox: false
      wrapTitleInBox: false
      includeTitle: false
      includeBreadcrumbs: false
```
