### ISSUE TITLE
Visibility modifiers kotlin

### ISSUE THREAD

**Issue by ridwan23** [orchidhq/Orchid#364]
How to customize the visibiity modifiers to include in documentation? i guess this plugin only generates public

**Comment by cjbrooks12** [comment]
The visibility filters are handled differently directly by the underlying documentation runners. Is this for Kotlin docs? You can pass additional args to Dokka with a config like the following:

```yaml
# config.yml
kotlindoc:
  showRunnerLogs: true
  sourceDirs:
    - './../../../../app/src/main/kotlin'
  args:
    - '-packageOptions'
    - 'com.example.hidden,+suppress'
```
